# Tensors

In [1]:
from __future__ import print_function
import torch

In [2]:
# 초기화되지 않은 5x3 행렬 생성
# 초기화되지 않았다, empty는 무슨 말인가
# empty에서 dtype을 FloatTensor로 하면 torch.tensor
x = torch.empty(5,3)
print(x)

tensor([[4.1327e-39, 8.9082e-39, 9.8265e-39],
        [9.4592e-39, 1.0561e-38, 1.0653e-38],
        [1.0469e-38, 9.5510e-39, 1.0378e-38],
        [8.9082e-39, 1.0653e-38, 1.1204e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39]])


In [3]:
# 무작위 초기화된 5x3 행렬
x = torch.rand(5, 3)
print(x)

tensor([[0.8236, 0.1276, 0.1543],
        [0.2442, 0.6494, 0.0233],
        [0.1053, 0.6483, 0.7932],
        [0.2451, 0.7399, 0.5602],
        [0.0195, 0.6693, 0.8621]])


In [4]:
# dtype이 long이다 == 64bit라는 뜻이래용 ㅎ
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x= torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float) # input x의 shape과 dtype을 override
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.3890, -2.3981,  0.8193],
        [-0.4417, -1.1747, -0.0643],
        [ 1.5099, -1.2550,  0.4490],
        [ 1.0723, -0.4860,  0.3253],
        [ 0.0392, -0.7645, -0.6206]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
x

tensor([[-1.3890, -2.3981,  0.8193],
        [-0.4417, -1.1747, -0.0643],
        [ 1.5099, -1.2550,  0.4490],
        [ 1.0723, -0.4860,  0.3253],
        [ 0.0392, -0.7645, -0.6206]])

# Operations

## 덧셈 1

In [10]:
y = torch.rand(5,3)
print(x + y)

tensor([[-0.9627, -2.1297,  1.5966],
        [-0.2526, -0.7755, -0.0176],
        [ 1.7458, -0.6543,  0.4882],
        [ 1.4745,  0.0558,  0.4605],
        [ 0.5101, -0.6308, -0.3677]])


## 덧셈 2

In [11]:
print(torch.add(x,y))

tensor([[-0.9627, -2.1297,  1.5966],
        [-0.2526, -0.7755, -0.0176],
        [ 1.7458, -0.6543,  0.4882],
        [ 1.4745,  0.0558,  0.4605],
        [ 0.5101, -0.6308, -0.3677]])


## 바꿔치기(in-place) 방식

In [12]:
# y에 x 더하기
y.add_(x)
print(y)

tensor([[-0.9627, -2.1297,  1.5966],
        [-0.2526, -0.7755, -0.0176],
        [ 1.7458, -0.6543,  0.4882],
        [ 1.4745,  0.0558,  0.4605],
        [ 0.5101, -0.6308, -0.3677]])


### 인덱싱 가능

In [15]:
y[2,:]

tensor([ 1.7458, -0.6543,  0.4882])

### 크기 변경

In [16]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### 값 얻어내기
- x.item()은 텐서 x에 하나의 값만 존재할 때 사용 가능

In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3118])
-0.31180232763290405


In [19]:
x = torch.empty(4,4)
print(x.item())

ValueError: only one element tensors can be converted to Python scalars

나머지 다양한 Tensor 연산들 <a href="http://pytorch.org/docs/torch">여기</a>

# Numpy 변환

### from Tensor to Numpy
- x.numpy()

In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
# 난 텐서에만 더했는데 텐서의 넘파이 형태인 b까지 변해버렸다.
# 같은 cpu 메모리 상에 있어서 변한다는데 뭔 말이고 ㅋ
# (Torch Tensor가 CPU 상에 있다면) Torch Tensor와 NumPy 배열은 
# 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### from Numpy to Tensor
- torch.from_numpy(x)

In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors
- .to 메도스를 사용해 Tensor를 어디로든 옮길 수 있다

In [25]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
