# Autograd: 자동 미분
- Tensor의 모든 연산에 대해 자동 미분을 제공한다.
- 역전파는 학습 과정의 매 단계마다 달라진다


## Tensor
- .requires_grad 를 True로 둔다: 해당 텐서에서 일어나는 모든 연산을 추적(track)한다. --> 계산 완료 후 .backward()를 통해 모든 변화도(gradient)를 자동 계산할 수 있다

- .grad_fn: 텐서가 연산을 하고 나면 grad_fn 속성을 갖게 된다.

- .detach(): 연산 기록으로부터 분리해서 추적을 방지

In [1]:
import torch

In [2]:
x = torch.ones(2,2, requires_grad=True) # 추적 하겠다
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


tensor x에 연산을 수행

In [4]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


y가 텐서 연산의 결과이므로 grad_fn을 가진 것을 확인

In [5]:
print(y.grad_fn)

<b>x의 연산 결과인 y에 다른 연산을 수행</b>

In [6]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
