## 1.1.1 파이토치의 구성
- torch: 메인 네임스페이스, 다양한 수학 함수 포함, Numpy와 같은 구조
- torch.autograd: 자동 미분을 위한 함수가 포함, 자동 미분 on/off, Function 클래스 포함
- torch.nn: 신경망 구서을 위한 데이터 구조나 레이어 등이 정의
- torch.optim: SGD를 중심으로 한 파라미터 최적화 알고리즘 구현되어 있음
- torch.utils.data: SGD의 반복 연상을 위한 미니 배치용 유틸리티 함수
- torch.onnx: 모델 export를 위한 사용

### 1.2.1 텐서 생성과 변환
- arange
- linespace
- logspace
- zeros
- ones

In [1]:
# 1.1 텐서 생성
import numpy as np
import torch

# 중첩 list를 지정
t = torch.tensor([[1,2],[3,4.]])

# device를 지정하면 GPU에 텐서 생성 가능
t = torch.tensor([[1,2],[3,4.]], device = 'cuda:0')

# dtype 지정 가능
t = torch.tensor([[1,2],[3,4.]], dtype=torch.float64)

# 0부터 9까지로 초기화된 1차원 텐서
t= torch.arange(0,10)

# 모든 값이 0인 100 x 10의 텐서를 작성 후 to 메서드로 GPU에 전송
t = torch.zeros(100,10).to("cuda:0")

# 정규 난수로 100 x 10의 텐서 작성
t = torch.randn(100,10)

# 텐서의 shape의 size 메서드로 확인 가능
t.size()


torch.Size([100, 10])

In [4]:
# 1.2 텐서 변환 예
# numpy 메서드를 사용해 ndarray로 변환
t = torch.tensor([[1,2],[3,4.]])
x = t.numpy()

# GPU 상의 텐서는 to 메서드로 CPU의 텐서로 이동(변환)할 필요가 있다.
t = torch.tensor([[1,2],[3,4.]], device='cuda:0')
x = t.to("cpu").numpy()

In [7]:
# 1.3 텐서의 인덱스 조작
t = torch.tensor([[1,2,3],[4,5,6.]])

# 스칼라 첨자 지정
t[0,2]

# 슬라이스로 지정
t[:,:2]

# 리스트로 지정
t[:,[1,2]]

# 마스크
t[t>3]

# 0,1의 요소를 100으로 설정
t[0,1]=100

# 슬라이스를 사용한 일괄 대입
t[:,1]= 200

# 마스크로 특정 요소만 치환
t[t>10] = 20

### 1.2.3 텐서연산

In [8]:
# 1.4 텐서 연산
# 길이 3인 벡터
v = torch.tensor([1,2,3.])
w = torch.tensor([0,10,20.])

# 2*3의 행렬
m = torch.tensor([[0,1,2],[100,200,300.]])

In [9]:
# 벡터와 스칼라의 덧셈
print(v)
v2 = v + 10
print(v2)

tensor([1., 2., 3.])
tensor([11., 12., 13.])


In [10]:
# 제곱
print(v)
v2 = v ** 2
print(v2)

tensor([1., 2., 3.])
tensor([1., 4., 9.])


In [11]:
# 동일 길이의 뺄셈
z = v - w
print(z)

tensor([  1.,  -8., -17.])


In [12]:
# 여러 조합
u = 2 * v - w / 10 + 6.0
print(u)

tensor([ 8.,  9., 10.])


In [13]:
# 행렬과 스칼라
m

tensor([[  0.,   1.,   2.],
        [100., 200., 300.]])

In [14]:
m2 = m * 2.0
m2

tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])

In [16]:
print(m) # 2,3
print(v) # 3, 
m3 = m + v # 브로드 캐스팅
print(m3)

tensor([[  0.,   1.,   2.],
        [100., 200., 300.]])
tensor([1., 2., 3.])
tensor([[  1.,   3.,   5.],
        [101., 202., 303.]])


In [17]:
print(m)
m4 = m + m 
print(m4)

tensor([[  0.,   1.,   2.],
        [100., 200., 300.]])
tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])


### 채널 변환

In [18]:
hwc_img_data = torch.rand(100,64,32,3)
hwc_img_data.size()

torch.Size([100, 64, 32, 3])

In [19]:
hwc_img_data.transpose(1,2).size()

torch.Size([100, 32, 64, 3])

In [20]:
hwc_img_data.transpose(1,2).transpose(1,3).size()

torch.Size([100, 3, 64, 32])

## 선형 대수의 대표연산자
- dot: 벡터 내적
- mv: 행렬 * 벡터
- mm: 행렬 * 행렬
- matmul: 인수에 따라 dot, mv, mm을 수행
- gesv: LU 분해를 사용한 연립방정식의 해
- eig, symeig: 고유값 분해
- svd: 특이값 분해

In [22]:
# 1.7 연산 예
m = torch.randn(100,10)
v = torch.randn(10)

# 내적 : 같은 index 끼리 곱하기
print(v)
d = torch.dot(v,v)
print(d)

tensor([-0.2016, -0.8494, -1.1139, -0.8698, -0.7927, -0.1147, -0.0324,  0.2516,
         1.5696,  0.0460])
tensor(5.9311)


In [24]:
# 행렬 x 벡터
print(m.size())
print(v.size())
v2 = torch.mv(m,v)
print(v2.size())

torch.Size([100, 10])
torch.Size([10])
torch.Size([100])


In [26]:
print(m.size())
print(m.t().size())
m2 = torch.mm(m.t(),m)
print(m2.size())

torch.Size([100, 10])
torch.Size([10, 100])
torch.Size([10, 10])


In [27]:
u,s,v = torch.svd(m)

In [30]:
print(u.size(),s.size(),v.size())

torch.Size([100, 10]) torch.Size([10]) torch.Size([10, 10])


## 1.3 텐서와 자동 미분

In [31]:
# 
x = torch.randn(100,3)
a = torch.tensor([1,2,3.], requires_grad = True)
print('x.size():',x.size())
print('a.size():',a.size())

# 
y = torch.mv(x,a)
print('y.size():',y.size())
o = y.sum()
print('o.size():',o.size())

x.size(): torch.Size([100, 3])
a.size(): torch.Size([3])
y.size(): torch.Size([100])
o.size(): torch.Size([])


In [36]:
o.backward()

In [37]:
a.grad != x.sum(0)

tensor([True, True, True])

In [32]:
o.item()

-5.578537940979004

In [33]:
x.grad is None

True